# site settings
title: CVAI Laboratory
subtitle: CVAI @ iLab.online
email: sjzhang@cqjtu.edu.cn
description: We are a Computer Vison and Artifical Intelligence(CVAI)<br /> research group at the ilab .
baseurl: "" # the subpath of your site, e.g. /blog
url:   # the base hostname & protocol for your site
author: ilab
street_address: No.66, Xuefu Road, Nan' an District
city: ChongQing
state: CQ
zip_code: 400074
country: China
phone: (+1) 951-213-1771

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6


collections:
  publications:
    output: false
    permalink: /:collection/:name


# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
